### ISSUE TITLE
Отступ в правой части сайта (мобильном меню)

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#11]
![2015-09-25 10-05-22](https://cloud.githubusercontent.com/assets/12879970/10094845/7c2f903e-636d-11e5-97a7-2caa64a5d8b7.png)

Слиплись кнопки входа через соц.сети: "Facebook" и "Яндекс", а так же чуть ниже текст "Я новый пользователь" слишком близко к блокам.

**Comment by anpleenko** [comment]
сделанно в #10 issue
