### ISSUE TITLE
Касяк с отображением сайта на ipade

### ISSUE THREAD

**Issue by allakin** [vseopro/vseopro#12]
Надо обязательно поправить

**Comment by allakin** [comment]
![](http://i.imgur.com/k6SvMKt.jpg)

**Comment by allakin** [comment]
![](http://i.imgur.com/lNW2ySm.jpg)

**Comment by allakin** [comment]
![](http://i.imgur.com/x7OjSDk.jpg)

**Comment by anpleenko** [comment]
В меню это не ошибка, там просто 2 меню в норм проекте оно одно будет.

**Comment by anpleenko** [comment]
Во втором скриншоте нужно подумать может както слово сократить.
