### ISSUE TITLE
Неверное появление мню

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#15]
![2015-10-16 13-14-00](https://cloud.githubusercontent.com/assets/12879970/10539404/057b11ec-7408-11e5-823a-98c069fee664.png)

Меню появляется слишком рано, это произошло из за жестко заданной границы появления, кстати не забудь учесть еще и то что мы полосу цветную убрали, теперь нужно правильно выровнять все.

**Comment by anpleenko** [comment]
это происходит потому что я вверх добавил меню
его если убрать то все норм

**Comment by vseopro** [comment]
А ты не забыл что еще и полосу цветную убрал, когда ты делал меню, она была. Учти это пожалуйста.
