### ISSUE TITLE
Подобрать иконки для групп прав

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#18]
![2015-10-20 12-54-51](https://cloud.githubusercontent.com/assets/12879970/10603964/edaf1642-7729-11e5-82bb-663b52d4cbd5.png)

Паша подбери иконки для групп прав на которых указывает стрелка.

**Comment by allakin** [comment]
И для чего будет только тупо одна и тоже иконка максимум что можно это сделать в цвет с текстом, но зачем.

**Comment by allakin** [comment]
Бредовая идея

**Comment by anpleenko** [comment]
а может просто человечка вставим?

**Comment by allakin** [comment]
Ну так и будет

**Comment by allakin** [comment]
Поэтому смысл плодить человечков

**Comment by anpleenko** [comment]
ну типо разбавить текст иконками, а то там все сливается

**Comment by allakin** [comment]
Все понятно стало

**Comment by allakin** [comment]
Готово макет в общем дб VSeopro_main.psd
