### ISSUE TITLE
Подсветка поля

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#19]
![2015-10-20 13-01-30](https://cloud.githubusercontent.com/assets/12879970/10604104/e1a9caee-772a-11e5-8b7d-614bbecd4763.png)

Сделать подсветку (выделения) поля ввода как на: http://ru.norton.com/  при входе в учетную запись или регистрацию, выделения поля смотреть внимательно.

**Comment by vseopro** [comment]
![2015-10-20 13-05-44](https://cloud.githubusercontent.com/assets/12879970/10604178/596cd74c-772b-11e5-9de5-c342a273e251.png)

**Comment by allakin** [comment]
Готово макет в общей всепро в дБ #19

**Comment by anpleenko** [comment]
не, закрывать надо когда вверстке появиться
