### ISSUE TITLE
Высота кнопки "Читать подробнее"

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#27]
![2015-10-29 13-42-41](https://cloud.githubusercontent.com/assets/12879970/10816333/23e65836-7e43-11e5-95ce-88377142a2c6.png)

Изменить высоту кнопки и убрать последую строчку в главной новости категории, что бы она нормально поместилась. Сделать кнопки такими как на скрине ниже (по высоте), что бы было и удобнее в дальнейшем, так как они будут одинаковыми.

![2015-10-29 13-42-08](https://cloud.githubusercontent.com/assets/12879970/10816394/9e92cefc-7e43-11e5-9478-ab66a55c9729.png)

**Comment by anpleenko** [comment]
готово
