### ISSUE TITLE
Неправильное отображение даты

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#28]
![2015-10-29 14-50-08](https://cloud.githubusercontent.com/assets/12879970/10817678/90afdd62-7e4c-11e5-9f32-ca0e612f4b37.png)

Дата должна быть формата 00 - день 00 - месяц - 0000 - год. То есть 02.12.2015 к примеру, не допускается использование даты в формате 2.12.2015

**Comment by anpleenko** [comment]
это я для теста сделал, тоесть там рандомно герерируется дата
