### ISSUE TITLE
Изменить иконки "браузеров" на иконки "мобильных устройств"

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#33]
![2015-11-16 14-01-13](https://cloud.githubusercontent.com/assets/12879970/11180319/e4936cce-8c6a-11e5-8140-7488135de6cc.png)

Изменить иконки браузеров на иконки мобильный устройств с анимацией при наведении как на сайте http://www.viadeo.com/profile/0022993iscr0fu17/ в футере их сайта пример этих кнопок как они должны быть.

**Comment by anpleenko** [comment]
ну круто, без реги хрен посмотриш

**Comment by vseopro** [comment]
Заходи смотри, вот логин: TDSko@yandex.ru, а вот пароль: 8242332812

P/S Как зайдешь перейди во вкладку "профиль" и в самом низу с права будут эти иконки.

**Comment by anpleenko** [comment]
осталась иконки блакбери

**Comment by anpleenko** [comment]
закрыто т.к. иконку от блакбери не нужно стало
