### ISSUE TITLE
Анимация иконок мобильных устройств

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#49]
![2016-03-07 10-51-59](https://cloud.githubusercontent.com/assets/12879970/13563437/be303fe0-e452-11e5-9c67-eb3100125f34.png)

Анимация иконок мобильных устройств нужна как на этом сайте в футере: http://www.viadeo.com/

Логин: TDSko@yandex.ru
Пароль: 8242332812 

Зайди глянь)

**Comment by anpleenko** [comment]
я посмотрел, да крутая штука, и своровать ее не проблема

**Comment by vseopro** [comment]
Ну вот и отлично, своруй ;)

**Comment by anpleenko** [comment]
да, думаю завтра попробую

**Comment by anpleenko** [comment]
за не надобностью закрываю
