### ISSUE TITLE
Анимация иконок соц.сетей в футере (точнее их описание)

### ISSUE THREAD

**Issue by vseopro** [vseopro/vseopro#50]
![2016-03-07 10-54-22](https://cloud.githubusercontent.com/assets/12879970/13563480/1dbf6198-e453-11e5-8181-31bd7c27a668.png)

Описание как и в значках мобильных устройств, все тоже самое но с вылетающим описанием.

**Comment by anpleenko** [comment]
за не надобностью закрываю
